### PR TITLE
Odds and Ends

### PR DESCRIPTION
**Pull request by profxj**
This is the companion to PR #1181 in the main repo (already merged).

I see it also includes the files for PR #1175 too.

### CODE REVIEW

**Comment by profxj** [comment]
Cooked v1.4.3 goes with this PR.

**Review by jhennawi — APPROVED** [review]

**Comment by finagle29** [comment]
I think the hardcoded spec1d and sensfunc files in `build_ql_masters` need to have the filenames changed to the new naming convention (i.e. change `2019Nov18T104704` to `20191118T104704`) because when I tried to run the dev suite tests for pypeit/PypeIt#1192, the MOSFIRE ql test failed because the std spec1d and sensfunc files weren't moved over from REDUX_OUT in `build_ql_masters`

**Comment by finagle29** [comment]
I just pushed a commit to address my last comment so looks good to me!

**Review by finagle29 — APPROVED** [review]

**Comment by finagle29** [comment]
merging

**Pull request merged**
