### PR TITLE
NOT/ALFOSC tests

### PR DESCRIPTION
**Pull request by Raindogjones**
Adds tests for newly added NOT/ALFOSC setups

### CODE REVIEW

**Comment by profxj** [comment]
@Raindogjones -- sorry for the trouble, but it looks like you
branched off of `master` instead of `develop`.   We use that
in this Repo too.

Can you pull in `develop` and resolve the conflicts?  Thx

**Comment by profxj** [comment]
I have rebased the PR to point at `develop`

**Comment by Raindogjones** [comment]
@profxj Sorry about that. Should be good to go now.

**Review by profxj — APPROVED** [review]

**Comment by profxj** [comment]
Thanks!

**Pull request merged**
