### PR TITLE
Expand supported DBSP configurations

### PR DESCRIPTION
**Pull request by finagle29**
Companion PR to pypeit/pypeit#1233

### CODE REVIEW

**Comment by finagle29** [comment]
```
./pypeit_test p200_dbsp_red -t 3
Running tests on the following instruments:
    p200_dbsp_red

Reducing data from p200_dbsp_red for the following setups:
    316_7500_d55
    1200_7100_d68
    600_10000_d55

Running tests in 3 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/316_7500_d55 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/1200_7100_d68 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/600_10000_d55 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/600_10000_d55 pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/1200_7100_d68 pypeit (without masters)
 3 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/316_7500_d55 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 3/3 TESTS (Masters ignored) ---
Testing Started at 2021-07-28T12:09:35.415121
Testing Completed at 2021-07-28T12:12:59.258567
Total Time: 0:03:23.843446
```

**Comment by finagle29** [comment]
```
./pypeit_test p200_dbsp_blue -t 3
Running tests on the following instruments:
    p200_dbsp_blue

Reducing data from p200_dbsp_blue for the following setups:
    600_4000_d55
    1200_5000_d68
    600_4000_d68

Running tests in 3 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/600_4000_d55 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/1200_5000_d68 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/600_4000_d68 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/1200_5000_d68 pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/600_4000_d68 pypeit (without masters)
 3 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/600_4000_d55 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 3/3 TESTS (Masters ignored) ---
Testing Started at 2021-07-28T12:15:04.627605
Testing Completed at 2021-07-28T12:17:16.338027
Total Time: 0:02:11.710422
```

**Comment by finagle29** [comment]
New setups added to dev-suite

- [ ] 1200/5000 D68
- [ ] 1200/5000 D55
- [ ] 1200/7100 D68
- [ ] 1200/9400 D55
- [ ] 300/3990 D55
- [ ] 600/10000 D55
- [ ] 600/4000 D68

**Comment by finagle29** [comment]
Running dev suite again

**Comment by finagle29** [comment]
```console
$ ./pypeit_test p200_dbsp_red -t 4
Running tests on the following instruments:
    p200_dbsp_red

Reducing data from p200_dbsp_red for the following setups:
    316_7500_d55
    1200_7100_d68
    600_10000_d55
    1200_9400_d55

Running tests in 4 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/316_7500_d55 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/600_10000_d55 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/1200_7100_d68 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_red/1200_9400_d55 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/600_10000_d55 pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/1200_7100_d68 pypeit (without masters)
 3 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/316_7500_d55 pypeit (without masters)
 4 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_red/1200_9400_d55 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 4/4 TESTS (Masters ignored) ---
Testing Started at 2021-07-29T10:30:05.770733
Testing Completed at 2021-07-29T10:32:37.317067
Total Time: 0:02:31.546334
```

**Comment by finagle29** [comment]
```console
$ ./pypeit_test p200_dbsp_blue -t 4
Running tests on the following instruments:
    p200_dbsp_blue

Reducing data from p200_dbsp_blue for the following setups:
    600_4000_d55
    1200_5000_d68
    600_4000_d68
    300_3990_d55
    1200_5000_d55

Running tests in 4 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/600_4000_d55 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/600_4000_d68 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/1200_5000_d55 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/1200_5000_d68 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/600_4000_d68 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped STARTED p200_dbsp_blue/300_3990_d55 pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/1200_5000_d68 pypeit (without masters)
 3 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/600_4000_d55 pypeit (without masters)
 4 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/1200_5000_d55 pypeit (without masters)
 5 passed/ 0 failed/ 0 skipped PASSED  p200_dbsp_blue/300_3990_d55 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 5/5 TESTS (Masters ignored) ---
Testing Started at 2021-07-29T10:33:21.296037
Testing Completed at 2021-07-29T10:36:09.565222
Total Time: 0:02:48.269185
```

**Review by profxj — APPROVED** [review]
great stuff

**Comment by finagle29** [comment]
merging!

**Pull request merged**
