### PR TITLE
Add templates and tests for additional modes of MMTO's Blue Channel and Binospec instruments

### PR DESCRIPTION
**Pull request by tepickering**
This PR includes the data used to generate templates for all commonly used gratings in the MMTO Blue Channel spectrograph as well as the 600 l/mm and 1000 l/mm gratings in Binospec. Pypeit files have been added to cover these new cases and the data has been uploaded into the google drive. The tests pass when run locally.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
thx for these!

Consider adding new `vet` tests that 
examine the output and insist on a certain
RMS be achieved.  

But I am approving with or without those.

**Comment by tepickering** [comment]
thanks. setting up `vet` tests would be a next level of effort. we definitely want to do that for `binospec` and vet the `pypeit` results against what the SAO pipeline produces. for `bluechannel` i want to wait and see if we can get its shutter fixed first before doing more work on it. the instrument may have finally reached the end of the line...

**Review by jhennawi — APPROVED** [review]
Great work @tepickering. Did you confirm that all of these tests pass?

**Comment by tepickering** [comment]
yes, i ran the new setups in the Dev Suite locally and they all passed.

**Pull request merged**
