### PR TITLE
README formatting

### PR DESCRIPTION
**Pull request by kbwestfall**
Goes with https://github.com/pypeit/PypeIt/pull/1488.  It just changes the formatting of the README file from markdown to rst.  This allows me to include it verbatim in the pypeit docs.

### CODE REVIEW

**Comment by badpandabear** [comment]
It looks like the code block under the "If you’re using Google File Stream" is broken. The vs code viewer doesn't like it and it also looks wrong on readthedocs.

**Comment by kbwestfall** [comment]
> It looks like the code block under the "If you’re using Google File Stream" is broken. The vs code viewer doesn't like it and it also looks wrong on readthedocs.

Good catch, @badpandabear !  I had an indentation error.  I think I've fixed it now.  Can you confirm?  (It may take a little while for readthedocs to update, but you can check in vs code.)

**Comment by debora-pe** [comment]
Hi @kbwestfall
I don't know if this is a problem with my machine, but I tried to run `./update_docs` and also `make html` but I was not able to generate the docs and I got this error:

```
wget -O ./include/dev_suite_readme.rst https://raw.githubusercontent.com/pypeit/PypeIt-development-suite/rst_readme/README.rst
make[1]: wget: No such file or directory
make[1]: *** [apirst] Error 1
make: *** [html] Error 2
```

**Comment by kbwestfall** [comment]
> Hi @kbwestfall I don't know if this is a problem with my machine, but I tried to run `./update_docs` and also `make html` but I was not able to generate the docs and I got this error:
> 
> ```
> wget -O ./include/dev_suite_readme.rst https://raw.githubusercontent.com/pypeit/PypeIt-development-suite/rst_readme/README.rst
> make[1]: wget: No such file or directory
> make[1]: *** [apirst] Error 1
> make: *** [html] Error 2
> ```

Hrmm...  Do you get the same error when you copy the command into a terminal window?  What happens if you add quotations around the url and/or the outptut file name?

**Comment by badpandabear** [comment]
Is it possible @debora-pe  doesn't have wget installed?

**Comment by debora-pe** [comment]
@kbwestfall @badpandabear 
Dusty you are absolutely right! I had a problem with wget (not installed). Now it works! Thank you!

**Review by badpandabear — APPROVED** [review]

**Pull request merged**
