### PR TITLE
Nod and shuffle and new wavelength solutions

### PR DESCRIPTION
**Pull request by profxj**
As titled.

Pairs with https://github.com/pypeit/PypeIt/pull/1078

### CODE REVIEW

**Review by badpandabear — APPROVED** [review]
Looks good, but the test_priority_list probably needs to be updated with all the new tests.

**Comment by profxj** [comment]
@badpandabear -- can you remind me where that info lies?

**Comment by badpandabear** [comment]
@profxj  test_priority_list is in the root directory of PypeIt-development-suite. It's rewritten when there's a full run of the dev suite with the order to run test setups in.

**Comment by profxj** [comment]
merging

**Pull request merged**
