### PR TITLE
Add P200_DBSP 1200/7100 D55 wavelength template

### PR DESCRIPTION
**Pull request by finagle29**
Companion PR to https://github.com/pypeit/PypeIt/pull/1849

### CODE REVIEW

**Comment by profxj** [comment]
Might you be able to add a DevSuite test too?

**Comment by finagle29** [comment]
It's just the .pypeit file that's needed to add the DevSuite test, right? I have a folder with the needed FITS files, but will need some help putting them in the right place (Google Drive?)

**Comment by kbwestfall** [comment]
> It's just the .pypeit file that's needed to add the DevSuite test, right? I have a folder with the needed FITS files, but will need some help putting them in the right place (Google Drive?)

Hi Milan.  I just responded to you about this in the #dbsp channel of the developer Slack.

**Review by kbwestfall — APPROVED** [review]
Thanks!

**Pull request merged**
